# ==============================
# Dev Profile - H2 File Database
# ==============================
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

# Verbose SQL & debug logging for development
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
logging.level.root=INFO
logging.level.com.app.quantitymeasurement=DEBUG
logging.level.org.springframework.security=DEBUG
logging.level.org.hibernate.SQL=DEBUG
