version: '3.8'

services:
  db:
    image: mysql:8.0
    container_name: quantity-mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD:-vikash@1006}
    ports:
      - "3307:3306"
    volumes:
      - ./init-db.sql:/docker-entrypoint-initdb.d/init-db.sql
      - mysql_data:/var/lib/mysql
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-p$DB_PASSWORD" ]
      interval: 10s
      timeout: 5s
      retries: 5

  eureka-server:
    build:
      context: ./eureka-server
      dockerfile: Dockerfile
    container_name: eureka-server
    ports:
      - "8761:8761"
    environment:
      - SERVER_PORT=8761
      - EUREKA_CLIENT_REGISTER_WITH_EUREKA=false
      - EUREKA_CLIENT_FETCH_REGISTRY=false

  admin-server:
    build:
      context: ./admin-server
      dockerfile: Dockerfile
    container_name: admin-server
    ports:
      - "9090:9090"
    env_file:
      - .env
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://db:3306/ambulance_db?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
    depends_on:
      db:
        condition: service_healthy
      eureka-server:
        condition: service_started

  api-gateway:
    build:
      context: ./api-gateway
      dockerfile: Dockerfile
    container_name: api-gateway
    ports:
      - "8080:8080"
    env_file:
      - .env
    depends_on:
      - eureka-server

  auth-service:
    build:
      context: ./auth-service
      dockerfile: Dockerfile
    container_name: auth-service
    ports:
      - "8083:8083"
    env_file:
      - .env
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://db:3306/quantitymeasurement_auth_db?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
    depends_on:
      db:
        condition: service_healthy
      eureka-server:
        condition: service_started

  user-service:
    build:
      context: ./user-service
      dockerfile: Dockerfile
    container_name: user-service
    ports:
      - "8082:8082"
    env_file:
      - .env
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://db:3306/quantitymeasurement_user_db?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
    depends_on:
      db:
        condition: service_healthy
      eureka-server:
        condition: service_started

  measurement-service:
    build:
      context: ./measurement-service
      dockerfile: Dockerfile
    container_name: measurement-service
    ports:
      - "8081:8081"
    env_file:
      - .env
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://db:3306/quantitymeasurement_db?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
    depends_on:
      db:
        condition: service_healthy
      eureka-server:
        condition: service_started

volumes:
  mysql_data:
